services:
  etcd:
    image: rapidfort/etcd:3.5
    network_mode: default
    restart: unless-stopped
    volumes:
      - ./etcd-data:/bitnami/etcd/data
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LOG_LEVEL=debug
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=${NAME1}
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://${IP_1}:2379
      - ETCD_INITIAL_CLUSTER=${NAME1}=http://${IP_1}:2380,${NAME2}=http://${IP_2}:2380,${NAME3}=http://${IP_3}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${IP_1}:2380
