services:

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    network_mode: default
    restart: unless-stopped
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - ./etcd-data:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LOG_LEVEL=debug
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_NAME=${ETCD_NAME1}
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:{CLIENT_PORT1}
      - ETCD_ADVERTISE_CLIENT_URLS=http://${IP_1}:{CLIENT_PORT1}
      - ETCD_INITIAL_CLUSTER=${ETCD_NAME1}=http://${IP_1}:{PEER_PORT1},${ETCD_NAME2}=http://${IP_2}:{PEER_PORT2},${ETCD_NAME3}=http://${IP_3}:{PEER_PORT3}
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:{PEER_PORT1}
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${IP_1}:{PEER_PORT1}
